name: Lowercase

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: write   # Allows pushing back to the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Convert filenames in /lang to lowercase
        run: |
          for file in lang/*; do
            # Extract just the filename, convert to lowercase
            lowercase=$(basename "$file" | tr '[:upper:]' '[:lower:]')
            if [ "$file" != "lang/$lowercase" ]; then
              mv "$file" "lang/$lowercase"
            fi
          done

      # Zip the /lang directory into a file called lang_files.zip
      - name: Create a ZIP of the lang files
        run: zip -r lang_files.zip lang

      # Erstellt einen neuen Tag mit Hilfe der Build-Nummer oder einem anderen eindeutigen Wert
      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # Einen Tag-Name generieren, z.B. mit der Build-Nummer
          TAG="release-${{ github.run_number }}"
          git tag $TAG
          git push origin $TAG

      # Create a release. We're using the commit SHA as a tag. 
      # You might prefer a more meaningful tag_name in a real scenario.
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: "Build for commit ${{ github.sha }}"

      # Upload the zipped file as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lang_files.zip
          asset_name: lang_files.zip
          asset_content_type: application/zip
