name: Lowercase

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: write   # Allows pushing back to the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Convert filenames in /lang to lowercase
        run: |
          for file in lang/*; do
            # Extract just the filename, convert to lowercase
            lowercase=$(basename "$file" | tr '[:upper:]' '[:lower:]')
            if [ "$file" != "lang/$lowercase" ]; then
              mv "$file" "lang/$lowercase"
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          # Only commit if there are changes
          git diff --quiet --cached || git commit -m "Convert all /lang filenames to lowercase"
          git push origin HEAD:${{ github.ref }}
